### ISSUE TITLE
[BUG] Hotkey with file open causes Links panel to open

### ISSUE THREAD

**Issue by ghost** [Vinzent03/obsidian-hotkeys-for-specific-files#10]
# Issue
When I have a hotkey'd file open, if I use the hotkey then it will open the "Outgoing Links" panel.

# To Reproduce
1. Set hotkey for file (eg. `planner/2023.05.Wk19.md`)
2. Open file in main panel
3. Make sure you're on a different panel view (eg. Outline, Tags, etc.)
4. Use hotkey
5. Right panel switches to "Outgoing Links"

![issue](https://github.com/Vinzent03/obsidian-hotkeys-for-specific-files/assets/2555670/e2a0473f-abe6-41be-93f4-f5d7f3346ce2)

**Comment by ghost** [comment]
Forgot to mention: If I disable the plugin, then this issue disappears, so I know it is the plugin. The issue also persists regardless of the shortcut that I use.

**Comment by Vinzent03** [comment]
Thanks for the bug report, should be fixed in 1.3.1

**Comment by ghost** [comment]
Dang you're good :)
