### ISSUE TITLE
[Feature] Possible to support {{date:____}} in hotkey?

### ISSUE THREAD

**Issue by ghost** [Vinzent03/obsidian-hotkeys-for-specific-files#11]
Hi,

I use Periodic Notes and would rather use this plugin's functionality to open my daily/weekly/monthly notes. Didn't see it documented and I tried `{{date:YYYY.MM.DD}}` but that didn't work. Is there support for this, or would that be possible to add in?

Thank you!

**Comment by Vinzent03** [comment]
It just took a while, but is available now! :tada:

**Comment by ghost** [comment]
Thank you!!  🙌  That’s awesome :)
