### ISSUE TITLE
Moment format - does not open today note

### ISSUE THREAD

**Issue by ricir** [Vinzent03/obsidian-hotkeys-for-specific-files#12]
I added the following format for file to open: 

`\D\i\a\r\y/YYYY-MM-DD\-\l\o\g.md`

(I understood the need for escape characters in order to define the folder and other characters outside the date format)

**Expected**: to open today's file:
`Diary\2023-01-29-log.md`

**What happens**: it opens
`Diary\2023-01-28-log.md`

(which is the last file I opened with the shortcut, yesterday)

If I close and reopen Obsidian the file for today is opened correctly.

**Comment by Vinzent03** [comment]
Should be fixed now

**Comment by ricir** [comment]
Yes, it is fixed, thank you.
