### ISSUE TITLE
Support automatically updating files in the configuration pane after renaming

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-hotkeys-for-specific-files#2]
In the current version, files cannot be opened any more with the specified hotkeys after they are renamed or moved into another folder. Is it possible to automatically update the settings in the configuration pane after moving or renaming files?

Not sure if the following issue is related:

[Update the list of Recent Files Tab after renaming a file · Issue #1 · tgrosinger/recent-files-obsidian](https://github.com/tgrosinger/recent-files-obsidian/issues/1)

**Comment by Vinzent03** [comment]
Is released!
