### ISSUE TITLE
Support opening the same file in different panes

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-hotkeys-for-specific-files#3]
In the current version, it seems that one cannot open the same file in different panes. I tried to open the same file in a different pane, then it navigates to the file that has been opened in another pane, instead of opening it again in another pane.

**Comment by FelipeRearden** [comment]
Hello @wenlzhang !

Obsidian has two hotkeys to open new versions of the same file: `Split Vertically` and `Split Horizontally` 

![Screen Shot 2021-07-09 at 06 02 16](https://user-images.githubusercontent.com/85180696/125053594-b1971580-e07b-11eb-876c-4903c4b8b20a.png)

This way we can have a set of hotkeys to satisfy two different purposes: open the same file in different panes and navigate to an open file!

I hope it helps!

**Comment by wenlzhang** [comment]
Hi @FelipeRearden

Thanks for the suggestions!

I am aware of the features you mentioned. Maybe I did not explain my use case clearly.

- I tend to open four panes (2-by-2), e.g. A, B, C and D, in Obsidian for better organizing and summarizing notes, e.g. summarizing things discussed at a meeting into other related notes.
- If I use the split window feature to duplicate a pane, e.g. pane A, a new pane E would be opened alongside pane A. However, sometimes I may want to duplicate pane A at the position of pane D. From there, I can navigate to linked notes of interest.

**Comment by Vinzent03** [comment]
This behavior was introduced by #1. I see your point and was aware that this use case gets broken by the implementation. However, I was not sure how much your use case is used. Adding a switch to switch between these two behavior would fix it?

**Comment by wenlzhang** [comment]
Maybe the example of using this feature for summarizing a meeting note was a bad example, as one may not assign a hotkey for a temporary file...

- Other than that, I would say my usage of the feature can be quite often. For instance, I may assign hotkeys for a few currently ongoing (important) project pages or Weekly Review notes, then I can navigate to these notes freely in different panes.
- Maybe it is a trivial thing, but having this feature supported also makes it more consistent with what one can do with the Hotkeys for starred files plugin, as one can open the same file in different panes there.

> Adding a switch to switch between these two behavior would fix it?

Which two behaviors do you mean?

**Comment by Vinzent03** [comment]
Behavior 1(old):
Opens a file, always in the current pane.
Behavior 2(new):
If the file is already opened in some pane (even sidebar) the focus switches to that pane. Otherwise, it's opened in the current pane.

**Comment by wenlzhang** [comment]
Then maybe a switch would be nice. 😃

**Comment by FelipeRearden** [comment]
Hello @Vinzent03 !

Thanks for the update. The `Prefer Existing Panes` option to switch between old and new behavior is working perfect in my test. 

Thank you very much for this!

Have a great day!
