### ISSUE TITLE
[Feature Request] Open Specific Notes as Hover Notes.

### ISSUE THREAD

**Issue by FelipeRearden** [Vinzent03/obsidian-hotkeys-for-specific-files#4]
Hello @Vinzent03 !!!!!!!!

There is a new plugin called [Hover Editor](https://github.com/nothingislost/obsidian-hover-editor) that bring to us the option of open files as popover. 

Would be a fantastic companion for Hotkeys for Specific Notes !!!! 

My FR is to add an option when creating a new hotkey to open the selected note as a Hover Note.

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by Vinzent03** [comment]
It took just almost a year, but it's now available in 1.3.0!

**Comment by FelipeRearden** [comment]
Thank you very much @Vinzent03 !!!!!!!!!!!!!!

Working perfect on Obsidian Mobile version 1.4.1

I wish you a fantastic day ☀️
