### ISSUE TITLE
Feature: open file in a new tab

### ISSUE THREAD

**Issue by Vasilic-Maxim** [Vinzent03/obsidian-hotkeys-for-specific-files#8]
Dear developer, I just wanted to take a moment to express my gratitude for creating such an amazing plugin. It has been a game-changer for me and I am truly grateful. I would like to share a suggestion that I believe would enhance its functionality even further.

It would be great if the shortcut could allow me to open a file in the current tab, as long as it's an empty one. If not, then the file could open in a new tab. This would streamline the process, as currently, I have to create an empty tab before using the shortcut to open a file.

Thank you for your time and for considering this suggestion. I really appreciate all the hard work you have put into this plugin.

**Comment by Vinzent03** [comment]
Thank you very much for your kind words! What do you think about a new command for each file to open it in another tab?

**Comment by Vasilic-Maxim** [comment]
Sounds great to me.

**Comment by Vinzent03** [comment]
Available in new release 1.3.0
